# 1. Server Port
server.port=8080

# 2. Redis Configuration (For Live HUD)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 3. Kafka Configuration (For Data Streaming)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=engo-group

# 4. H2 Database (For Trip History)
spring.datasource.url=jdbc:h2:mem:engodb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true

# Tell the app where the Admin Server is (it's right here!)
spring.boot.admin.client.url=http://localhost:8080

# Expose all the "vitals" (RAM, CPU, Threads) so the Admin can see them
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always